-- CREATE THE CLIENTES TABLE
CREATE TABLE IF NOT EXISTS EMASA.CLIENTES (
  ID INT NOT NULL,
  NOME_CLIENTE VARCHAR(50) NOT NULL,
  TELEFONE VARCHAR(10) NOT NULL,
  EMAIL VARCHAR(40) NOT NULL,
  CNPJ VARCHAR(14) NOT NULL,
  DATA_REGISTRO DATE NOT NULL,
 CONSTRAINT PK_CLIENTES PRIMARY KEY (ID) 
);

-- CREATE THE ENDERECOS TABLE
CREATE TABLE IF NOT EXISTS EMASA.ENDERECOS (
	ID INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	LOGRADOURO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	CEP VARCHAR(10) NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	DATA_REGISTRO DATE NOT NULL,
	CONSTRAINT PK_ENDERECOS PRIMARY KEY (ID),
	INDEX FK_ENDERECO_CLIENTE (ID_CLIENTE ASC) VISIBLE,
	CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES EMASA.CLIENTES (ID)
);

-- CREATE THE VEICULOS TABLE
CREATE TABLE IF NOT EXISTS EMASA.VEICULOS (
	PLACA VARCHAR(10) NOT NULL,
	ID_CLIENTE INT NULL DEFAULT NULL,
	MARCA VARCHAR(50) NULL,
	MODELO VARCHAR(50) NULL,
	ALTURA_CACAMBA DECIMAL(10,2) NOT NULL,
	LARGURA_CACAMBA DECIMAL(10,2) NOT NULL,
	COMPRIMENTO_CACAMBA DECIMAL(10,2) NOT NULL,
	DATA_REGISTRO DATE NOT NULL,
	CONSTRAINT PK_VEICULOS PRIMARY KEY (PLACA),
	INDEX FK_VEICULOS_CLIENTES (ID_CLIENTE ASC) VISIBLE,
	CONSTRAINT FK_VEICULOS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES EMASA.CLIENTES (ID)
);

-- CREATE THE MOTORISTAS TABLE
CREATE TABLE IF NOT EXISTS EMASA.MOTORISTAS (
  CPF VARCHAR(11) NOT NULL COMMENT 'Um número inteiro que identifica exclusivamente cada motorista.',
  PLACA VARCHAR(10) NULL DEFAULT NULL COMMENT 'Uma string de até 10 caracteres que se refere à placa do veículo atribuído ao motorista. Este campo é opcional, pois um motorista pode não estar vinculado a um veículo.',
  NOME VARCHAR(50) NOT NULL COMMENT 'Uma string de até 50 caracteres que contém o nome do motorista.',
  TELEFONE VARCHAR(15) NOT NULL COMMENT 'Uma string de até 15 caracteres que contém o número de telefone do motorista.',
  EMAIL VARCHAR(50) NOT NULL COMMENT 'Uma string de até 50 caracteres que contém o endereço de e-mail do motorista.',
  PRIMARY KEY (CPF),
  INDEX FK_MOTORISTAS_VEICULOS (PLACA ASC) VISIBLE,
  UNIQUE INDEX CPF_UNIQUE (CPF ASC) VISIBLE,
  CONSTRAINT FK_MOTORISTAS_VEICULOS FOREIGN KEY (PLACA) REFERENCES EMASA.VEICULOS (PLACA) ON DELETE CASCADE
  );

-- CREATE THE PRODUTOS TABLE
CREATE TABLE IF NOT EXISTS EMASA.PRODUTOS (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  TIPO VARCHAR(10) NULL,
  DESCRICAO TEXT NULL DEFAULT NULL,
  PRECO DECIMAL(10,2) NOT NULL,
  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
  );

-- CREATE THE ESTOQUE TABLE 
  CREATE TABLE IF NOT EXISTS EMASA.ESTOQUE (
  ID INT NOT NULL COMMENT 'Um número inteiro que identifica exclusivamente cada registro no estoque.',
  CAPACIDADE_MAXIMA DECIMAL(10,2) NOT NULL COMMENT 'Um número decimal que indica a capacidade máxima de armazenamento do estoque em metros cúbicos.',
  DATA_ATUALIZACAO_ESTOQUE DATE NOT NULL COMMENT 'Uma data que indica a data da última atualização do estoque.',
  LOCALIZACAO VARCHAR(45) NULL COMMENT 'Uma string de até 45 caracteres que indica a localização do estoque. Este campo é opcional.',
  VOLUME DECIMAL(10,2) NULL COMMENT 'Um número decimal que indica o volume atual de produtos armazenados no estoque em metros cúbicos. Este campo é opcional.',
  TIPO VARCHAR(45) NULL COMMENT 'Uma string de até 45 caracteres que indica o tipo de produto armazenado no estoque. Este campo é opcional.',
  ID_PRODUTO INT NULL,
  CONSTRAINT PK_ESTOQUE PRIMARY KEY (ID),
  INDEX FK_ESTOQUE_PRODUTOS_idx (ID_PRODUTO ASC) VISIBLE,
  CONSTRAINT FK_ESTOQUE_PRODUTOS FOREIGN KEY (ID_PRODUTO) REFERENCES EMASA.PRODUTOS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- CREATE THE VENDAS TABLE
CREATE TABLE IF NOT EXISTS EMASA.VENDAS (
  ID INT NOT NULL AUTO_INCREMENT,
  DATA_VENDA DATE NOT NULL,
  ID_PRODUTO INT NOT NULL,
  ID_ESTOQUE INT NOT NULL,
  ID_CLIENTE INT NOT NULL,
  ID_ENDERECO INT NOT NULL,
  ID_MOTORISTA INT NOT NULL,
  ID_VEICULO VARCHAR(10) NOT NULL,
  QUANTIDADE DECIMAL(10,2) NOT NULL,
  PRECO_TOTAL DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (DATA_VENDA),
  INDEX FK_VENDA_PRODUTO (ID_PRODUTO ASC) VISIBLE,
  INDEX FK_VENDA_CLIENTES (ID_CLIENTE ASC) VISIBLE,
  INDEX FK_VENDAS_ESTOQUE (ID_ESTOQUE ASC) VISIBLE,
  UNIQUE INDEX ID_UNIQUE (ID ASC) INVISIBLE,
  INDEX FK_VENDAS_ENDERECO_idx (ID_ENDERECO ASC) INVISIBLE,
  INDEX FK_VENDAS_MOTORISTA_idx (ID_MOTORISTA ASC) INVISIBLE,
  INDEX FK_VENDAS_VEICULO_idx (ID_VEICULO ASC) VISIBLE,
  CONSTRAINT FK_VENDA_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES EMASA.CLIENTES (ID),
  CONSTRAINT FK_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES EMASA.PRODUTOS (ID),
  CONSTRAINT FK_VENDAS_ESTOQUE FOREIGN KEY (ID_ESTOQUE) REFERENCES EMASA.ESTOQUE (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_VENDAS_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES EMASA.ENDERECOS (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_VENDAS_MOTORISTA FOREIGN KEY (ID_MOTORISTA) REFERENCES EMASA.MOTORISTAS (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_VENDAS_VEICULO FOREIGN KEY (ID_VEICULO) REFERENCES EMASA.VEICULOS (PLACA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

